language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  global:
    - ILLUMINATE_VERSION=5.8.*

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.0.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.0.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.0.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.7.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.0.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.1.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.2.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.3.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.4.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.5.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.6.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.7.*

before_install:
  - travis_retry composer self-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
  - vendor/bin/phpunit
